kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: openssl-tpm2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openssl-tpm2
  template:
    metadata:
      labels:
        app: openssl-tpm2
      annotations:
    spec:
      affinity:
       podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - openssl-tpm2
                topologyKey: kubernetes.io/hostname
      containers:
        - name: openssl-tpm2
          image: quay.io/dfroehli/openssl_tpm2
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-tls-certs
              mountPath: /host/certs
          ports:
            - containerPort: 8443
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 180
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

      serviceAccountName: "privileged-tpmaccess"
      nodeSelector:
        tpm2: present
      volumes:
       - name: host-tls-certs
         hostPath:
           path: /etc/pki/tls/edgeTPM
           type: 'DirectoryOrCreate'
