kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: openssl-tpm2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: openssl-tpm2
  template:
    metadata:
      labels:
        app: openssl-tpm2
      annotations:
    spec:
      containers:
        - name: openssl-tpm2
          image: quay.io/dfroehli/openssl_tpm2
          ports:
            - containerPort: 8443
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /host/dev/tpmrm0
            name: hostdev-tpmrm0
      serviceAccountName: "privileged-tpmaccess"
      nodeSelector:
        tpm2: present
      volumes:
       - name: hostdev-tpmrm0
         hostPath:
           path: /dev/tpmrm0
           type: 'CharDevice'
